-- Airbnb Management Database
-- Schema definition (tables, keys, constraints)

DROP DATABASE IF EXISTS airbnbmanagement;
CREATE DATABASE airbnbmanagement;
USE airbnbmanagement;

-- Drop tables in FK-safe order
DROP TABLE IF EXISTS RENTS;
DROP TABLE IF EXISTS RENTERPHONENUM;
DROP TABLE IF EXISTS RENTER;
DROP TABLE IF EXISTS FIXES;
DROP TABLE IF EXISTS CONTRACTOR;
DROP TABLE IF EXISTS OWNED;
DROP TABLE IF EXISTS MANAGED;
DROP TABLE IF EXISTS UNIT;
DROP TABLE IF EXISTS CLEANER;
DROP TABLE IF EXISTS OWNER;

-- OWNER
CREATE TABLE OWNER (
  OWNERID VARCHAR(3),
  CONSTRAINT OWNER_PK PRIMARY KEY (OWNERID)
);

-- CLEANER (self-referencing trainer)
CREATE TABLE CLEANER (
  CLEANERID VARCHAR(3),
  HIREDATE DATE,
  TRAINERID VARCHAR(3),
  CONSTRAINT CLEANER_PK PRIMARY KEY (CLEANERID),
  CONSTRAINT CLEANER_FK_TRAINER
    FOREIGN KEY (TRAINERID) REFERENCES CLEANER(CLEANERID)
);

-- UNIT (cleaner assigned)
CREATE TABLE UNIT (
  UNITID VARCHAR(3),
  NUMBATH DECIMAL(3,1),
  NUMBED INT,
  RATING DECIMAL(3,2),
  MAXGUESTS INT,
  STREET VARCHAR(30),
  ZIP VARCHAR(30),
  CITY VARCHAR(30),
  STATE VARCHAR(30),
  CLEANERID VARCHAR(3),
  CONSTRAINT UNIT_PK PRIMARY KEY (UNITID),
  CONSTRAINT UNIT_FK_CLEANER
    FOREIGN KEY (CLEANERID) REFERENCES CLEANER(CLEANERID)
);

-- MANAGED units
CREATE TABLE MANAGED (
  UNITID VARCHAR(3),
  OWNERID VARCHAR(3),
  BOOKINGFEE DECIMAL(20,2),
  MANAGESTARTDATE DATE,
  CONSTRAINT MANAGED_PK PRIMARY KEY (UNITID),
  CONSTRAINT MANAGED_FK_UNIT
    FOREIGN KEY (UNITID) REFERENCES UNIT(UNITID),
  CONSTRAINT MANAGED_FK_OWNER
    FOREIGN KEY (OWNERID) REFERENCES OWNER(OWNERID)
);

-- OWNED units
CREATE TABLE OWNED (
  UNITID VARCHAR(3),
  CONSTRAINT OWNED_PK PRIMARY KEY (UNITID),
  CONSTRAINT OWNED_FK_UNIT
    FOREIGN KEY (UNITID) REFERENCES UNIT(UNITID)
);

-- CONTRACTOR
CREATE TABLE CONTRACTOR (
  CONTRACTORID VARCHAR(3),
  CONTRACTORNAME VARCHAR(50),
  CONSTRAINT CONTRACTOR_PK PRIMARY KEY (CONTRACTORID)
);

-- FIXES (maintenance work)
CREATE TABLE FIXES (
  CONTRACTORID VARCHAR(3),
  UNITID VARCHAR(3),
  FIXDATE DATE,
  PAYMENTAMOUNT DECIMAL(20,2),
  CONSTRAINT FIXES_PK PRIMARY KEY (CONTRACTORID, UNITID, FIXDATE),
  CONSTRAINT FIXES_FK_UNIT
    FOREIGN KEY (UNITID) REFERENCES UNIT(UNITID),
  CONSTRAINT FIXES_FK_CONTRACTOR
    FOREIGN KEY (CONTRACTORID) REFERENCES CONTRACTOR(CONTRACTORID)
);

-- RENTER
CREATE TABLE RENTER (
  RENTERID VARCHAR(3),
  FIRSTNAME VARCHAR(50),
  LASTNAME VARCHAR(50),
  CONSTRAINT RENTER_PK PRIMARY KEY (RENTERID)
);

-- RENTER phone numbers (multi-valued attribute)
CREATE TABLE RENTERPHONENUM (
  RENTERID VARCHAR(3),
  PHONENUM VARCHAR(15),
  CONSTRAINT RENTERPHONENUM_PK PRIMARY KEY (RENTERID, PHONENUM),
  CONSTRAINT RENTERPHONENUM_FK_RENTER
    FOREIGN KEY (RENTERID) REFERENCES RENTER(RENTERID)
);

-- RENTS (bookings)
CREATE TABLE RENTS (
  UNITID VARCHAR(3),
  RENTERID VARCHAR(3),
  BOOKINGDATE DATE,
  STARTDATE DATE,
  ENDDATE DATE,
  NUMGUESTS INT,
  CONSTRAINT RENTS_PK PRIMARY KEY (UNITID, RENTERID, STARTDATE),
  CONSTRAINT RENTS_FK_UNIT
    FOREIGN KEY (UNITID) REFERENCES UNIT(UNITID),
  CONSTRAINT RENTS_FK_RENTER
    FOREIGN KEY (RENTERID) REFERENCES RENTER(RENTERID)
);

